#!/bin/bash
set -euo pipefail

GPSD_DEFAULTS="/etc/default/gpsd"

FACTORY_BAUD=9600
TARGET_BAUD=115200
TARGET_RATE=100      # ms = 10 Hz
TARGET_MODEL=5       # Sea
DEFAULT_PROTVER=18
UBXTOOL_WAIT=2       # seconds
PROBE_RETRIES=3      # MON-VER attempts before falling back to DEFAULT_PROTVER
PROBE_RETRY_DELAY=1  # seconds between them; the load that eats a reply is bursty
SNIFF_SECONDS=3      # passive listen window per candidate baud
SNIFF_FLUSH=0.5      # discard window for bytes framed at the previous baud
SNIFF_MAX_BYTES=8192 # cap on a sample: enough to decide, bounded parse cost
DETECT_RETRIES=2     # detection attempts before declaring a device silent
UBX_SYNC_MIN=3       # UBX sync headers needed to call a sample a receiver stream
NO_RECEIVER_RC=2     # configure_device: the port is idle and unheld — nothing fitted
QUIET_MAX_BYTES=1    # bytes a listen window may yield and still count as silence
READ_CONTENDED_RC=2  # read_port: the port's rate changed under us mid-listen

# Set by detect_baud.
DETECTED_BAUD=""
DETECTED_RX_DISABLED=0
# Set when a listen was invalidated by another process changing the port's rate.
# Sticky across retries, so configure_device clears it per device.
DETECTED_CONTENDED=0
# Where configure_device last saw a receiver, even if configuring it failed.
# main uses this to keep gpsd's speed matched to the hardware's actual state.
RECEIVER_BAUD=""

get_uart_devices() {
    if [ ! -f "$GPSD_DEFAULTS" ]; then
        return
    fi
    local devices
    # gpsd defaults file is generated by our build system (root-owned, simple key=value)
    # shellcheck source=/dev/null
    devices=$(. "$GPSD_DEFAULTS" && echo "${DEVICES:-}")
    for dev in $devices; do
        case "$dev" in
            /dev/ttyAMA*) echo "$dev" ;;
        esac
    done
}

# Listen to the port without transmitting. Transmitting at a baud the receiver
# is not running at produces framing errors, and M8 firmware disables its UART
# receiver after more than 100 of them; HALPI2 has no GNSS reset line, so that
# state survives a warm reboot. Detection therefore has to be read-only.
read_port() {
    local device="$1" baud="$2"
    stty -F "$device" "$baud" raw -echo -hupcl clocal 2>/dev/null || return 1
    # Bytes already sitting in the tty queue were framed by the UART at the
    # PREVIOUS baud, and changing the rate does not re-frame or discard them.
    # Sampling straight after the switch therefore reads a valid stream from the
    # old rate and authenticates the new one -- observed on halpi.hurma, where a
    # listen at 9600 returned 11416 bytes (four times what 9600 can carry in the
    # window) of the receiver's real 115200 UBX output. Drain first, discard it,
    # and sample only bytes the UART framed at the rate under test.
    timeout "$SNIFF_FLUSH" cat "$device" >/dev/null 2>&1 || true
    # cat writes each read through unbuffered, so the sample collected before
    # timeout kills it still reaches the caller. 124 (timed out) is the norm.
    #
    # Dropping NULs changes nothing about the sample -- the command substitution
    # that captures it discards them regardless -- but doing it here keeps bash
    # from logging "ignored null byte in input" on every read. UBX binary is full
    # of them, so that is one warning per baud per boot on a healthy device.
    #
    # Capped because the sample feeds string parsers that are superlinear in its
    # length, and because deciding needs a few sentences, not three seconds of
    # stream. Without the cap a full window at 115200 is ~34 KB and the parsers
    # cost seconds of pure bash per boot, inside a 60 s unit budget.
    timeout "$SNIFF_SECONDS" cat "$device" 2>/dev/null \
        | head -c "$SNIFF_MAX_BYTES" | LC_ALL=C tr -d '\000' || true

    # termios belongs to the port, not to our descriptor. Another process opening
    # the device mid-listen re-sets the rate under us, and the bytes we just read
    # were then framed at ITS rate while we credit them to ours -- after which we
    # would transmit at a rate the receiver is not running at. Discard a sample
    # whose rate no longer matches the one under test.
    #
    # Reported apart from an empty sample, because it is not silence: it is proof
    # that something else touched the port while we listened, which is one of the
    # faults the caller must not mistake for an absent receiver.
    local now
    now=$(stty -F "$device" speed 2>/dev/null | tr -dc '0-9') || return 1
    [ "$now" = "$baud" ] || return "$READ_CONTENDED_RC"
}

# How many bytes the port produced in one listen window, NULs included.
#
# read_port's sample cannot answer this. It comes back through a command
# substitution, which drops NUL bytes, and a receiver read at a rate it is not
# using produces mostly those -- so a talking port can arrive looking empty.
# Measured on an unfitted HALPI2 UART: ten windows, zero bytes every time. Any
# traffic at all therefore means something is transmitting.
port_byte_count() {
    local device="$1" baud="$2"
    stty -F "$device" "$baud" raw -echo -hupcl clocal 2>/dev/null || return 1
    timeout "$SNIFF_FLUSH" cat "$device" >/dev/null 2>&1 || true
    # The count is on stdout; the status is not about the count. timeout kills
    # cat and returns 124, and pipefail carries that out of the pipeline, so a
    # caller writing `n=$(port_byte_count ...) || n=0` throws away a real
    # measurement on every single call and reads a talking port as empty.
    { timeout "$SNIFF_SECONDS" cat "$device" 2>/dev/null \
        | head -c "$SNIFF_MAX_BYTES" | wc -c | tr -dc '0-9'; } || true
}

# tcgetattr and nothing else: reading the port's speed transmits not one bit,
# but it fails when the device cannot be opened or is not a serial port at all.
# That distinction is otherwise lost -- read_port folds an open failure into the
# same `return 1` as an empty read.
port_usable() {
    stty -F "$1" speed >/dev/null 2>&1
}

# A valid checksum is what separates NMEA from the line noise a mismatched baud
# produces; a bare '$' appearing in noise is not enough to accept a rate.
valid_nmea_line() {
    local line="${1%$'\r'}" body expected sum=0 i char
    [[ "$line" =~ ^\$([A-Za-z0-9]+,[^*]*)\*([0-9A-Fa-f]{2})$ ]] || return 1
    body="${BASH_REMATCH[1]}"
    expected=$((16#${BASH_REMATCH[2]}))
    for ((i = 0; i < ${#body}; i++)); do
        printf -v char '%d' "'${body:i:1}"
        sum=$((sum ^ char))
    done
    [ "$sum" -eq "$expected" ]
}

# NMEA 0183 is 7-bit ASCII, so every other byte in a sample is noise by
# definition -- and leaving it in corrupts the text operations themselves. Under
# glibc in a UTF-8 locale, `read` treats a stray high byte as the start of a
# multi-byte character and consumes the newline that follows it, so a valid
# sentence preceded by line noise gets merged into the noise line and is never
# seen. That is not hypothetical here: the re-listen after a baud switch reads
# the tail of the old rate as high-bit garbage, immediately followed by clean
# sentences at the new one.
#
# LC_ALL=C because this is a byte filter fed deliberately invalid text: BSD tr
# aborts with "Illegal byte sequence" in a UTF-8 locale. The trailing newline is
# required, not cosmetic -- read discards a final line that is not
# newline-terminated, and a sample can end mid-sentence.
ascii_only() {
    printf '%s\n' "$1" | LC_ALL=C tr -cd '\11\12\15\40-\176'
}

has_valid_nmea() {
    local line
    while IFS= read -r line; do
        valid_nmea_line "$line" && return 0
    done < <(ascii_only "$1")
    return 1
}

# The receiver announces this state itself, in a normal NMEA sentence, and keeps
# transmitting afterwards -- so it is visible exactly where a passive read looks.
# Only reachable in NMEA mode, which is where it matters: a receiver that latched
# this way was never successfully configured, so it is still at factory defaults.
rx_disabled() {
    [[ "$(ascii_only "$1")" == *"UART RX was disabled"* ]]
}

# A receiver is not necessarily speaking NMEA. gpsd switches u-blox devices into
# UBX binary mode when it takes over, and that survives a warm reboot, so on any
# device gpsd has already driven the stream is pure UBX with no NMEA in it at
# all. Treating NMEA as the only sign of life would report those as absent and
# skip configuring them entirely.
#
# Byte-boundary safety: the hex dump is delimited per byte, so "b5:62" cannot
# match across the seam of an unrelated pair such as ab 56 2c.
ubx_sync_count() {
    local hex
    hex=$(printf '%s' "$1" | od -An -tx1 -v | tr -s ' \n' ':')
    # grep, not repeated ${rest#*b5:62} stripping: that re-scans from the start
    # on every iteration, so the no-match path -- which is every wrong-rate
    # sample -- is quadratic. No `head` in the pipeline: it would close the pipe
    # early and the resulting SIGPIPE reads as a failure under pipefail.
    printf '%s' "$hex" | { grep -o 'b5:62' || true; } | wc -l | tr -dc '0-9'
}

has_ubx_frames() {
    [ "$(ubx_sync_count "$1")" -ge "$UBX_SYNC_MIN" ]
}

# Either protocol proves a receiver is present and the baud is right.
has_receiver_output() {
    has_valid_nmea "$1" || has_ubx_frames "$1"
}

detect_once() {
    local device="$1" baud sample rc
    DETECTED_BAUD=""
    DETECTED_RX_DISABLED=0

    # Target first: an already-configured receiver is the common case, and
    # ordering only costs a listen window, never a mismatched transmission.
    for baud in "$TARGET_BAUD" "$FACTORY_BAUD"; do
        rc=0
        sample=$(read_port "$device" "$baud") || rc=$?
        [ "$rc" -eq "$READ_CONTENDED_RC" ] && DETECTED_CONTENDED=1
        [ "$rc" -eq 0 ] || continue
        has_receiver_output "$sample" || continue
        DETECTED_BAUD="$baud"
        if rx_disabled "$sample"; then
            DETECTED_RX_DISABLED=1
        fi
        return 0
    done
    return 1
}

# Concluding too early is the quiet failure, not the loud one: a receiver still
# initialising at cold boot, or one whose window landed between sentences at
# 1 Hz, is written off as absent and the unit exits 0 with the receiver left
# unconfigured until the next reboot. These retries and the traffic check in
# configure_device are the whole margin against that, so do not trade them away.
# Retrying costs nothing on the common path, which succeeds on the first try.
detect_baud() {
    local device="$1" attempt=1
    while :; do
        detect_once "$device" && return 0
        [ "$attempt" -ge "$DETECT_RETRIES" ] && return 1
        echo "Nothing heard on $device, retrying ($attempt/$DETECT_RETRIES)..."
        attempt=$((attempt + 1))
    done
}

# Who else has the port open, named from /proc. Neither fuser nor lsof is on a
# HaLOS image, and the kernel already exports what they would report.
#
# A receiver that was never fitted and a receiver whose bytes another process is
# consuming both read as silence, and only the second is a fault, so the fault
# has to be evidenced rather than assumed.
#
# `-ef` rather than comparing readlink's output: it forks nothing, so the scan
# costs 11 ms against 736 open descriptors instead of 680 ms, and it compares the
# device's inode, which matches a holder that opened the same node by another
# path -- a container with the UART mapped under a different name renders its own
# mount namespace's path in /proc, and a string comparison misses it. Descriptors
# on sockets and pipes resolve to nothing and fall out for free.
#
# Ours are excluded by process group, not by pid. Every subshell this script
# forks inherits its descriptors, including the command substitution that calls
# this and any pipeline around it, and all of them share the script's group --
# so a pid list would have to know how the caller wrapped the call, and would
# report the script's own descriptor as a foreign holder when it guessed wrong.
port_holders() {
    local device="$1" fd pid comm stat pgid our_pgid
    local -a found=()
    stat=$(< /proc/self/stat) || return 0
    read -r _ _ our_pgid _ <<< "${stat##*) }"
    for fd in /proc/[0-9]*/fd/*; do
        [ "$fd" -ef "$device" ] || continue
        pid=${fd#/proc/}
        pid=${pid%%/*}
        # comm is parenthesised in stat and can contain spaces, so the fields are
        # counted from the last ')' rather than from the start of the line.
        stat=$(< "/proc/$pid/stat") || continue
        read -r _ _ pgid _ <<< "${stat##*) }"
        [ "$pgid" = "$our_pgid" ] && continue
        # Filtered because comm is 15 bytes of the process's own choosing,
        # control characters included, and this reaches a terminal.
        comm=""
        read -r comm < "/proc/$pid/comm" 2>/dev/null || true
        comm=${comm//[![:print:]]/}
        found+=("${comm:-?}[${pid}]")
    done
    [ "${#found[@]}" -eq 0 ] && return 0
    printf '%s\n' "${found[@]}" | sort -u | paste -sd ' ' -
}

probe_receiver() {
    local device="$1" baud="$2" output
    output=$(ubxtool -f "$device" -s "$baud" -w "$UBXTOOL_WAIT" -p MON-VER 2>/dev/null)
    # ubxtool exits 0 even with no response; validate actual UBX output.
    # Match in-shell, not via `echo | grep -q`: grep -q closes the pipe on the
    # first match, and under `set -o pipefail` echo's resulting SIGPIPE reads as
    # a false "no receiver" whenever the receiver is already streaming NAV.
    [[ "$output" == *"MON-VER"* ]] || return 1
    echo "$output"
}

# The receiver's protocol version, or non-zero if it would not say.
#
# Retried because the reply goes missing on a link the receiver is already
# filling: measured against a live 10 Hz MAX-M8Q at 115200, 7 of 90 polls got no
# answer. A longer wait does not help -- an oversubscribed receiver drops the
# reply rather than delaying it -- so the retries are spaced instead, the load
# that swallows one being bursty.
probe_protver() {
    local device="$1" baud="$2" attempt=1 output
    while :; do
        if output=$(probe_receiver "$device" "$baud"); then
            parse_protver "$output"
            return 0
        fi
        [ "$attempt" -ge "$PROBE_RETRIES" ] && return 1
        sleep "$PROBE_RETRY_DELAY"
        attempt=$((attempt + 1))
    done
}

# Bash regex, not `grep -oP`: -P is a GNU extension, so on BSD grep the match
# silently fails and every receiver is addressed with the default version.
parse_protver() {
    if [[ "$1" =~ PROTVER=([0-9]+) ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        echo "$DEFAULT_PROTVER"
    fi
}

# Output discarded, not just stderr: while ubxtool waits it prints every UBX
# message the receiver sends, which is hundreds of lines per invocation. No
# caller reads it -- only probe_receiver's output is parsed -- and this unit's
# own messages have to stay findable in the journal.
run_ubxtool() {
    local device="$1" baud="$2" protver="$3"
    shift 3
    ubxtool -f "$device" -s "$baud" -P "$protver" -w "$UBXTOOL_WAIT" "$@" >/dev/null 2>&1
}

configure_device() {
    local device="$1"
    echo "Configuring $device..."

    RECEIVER_BAUD=""
    DETECTED_CONTENDED=0

    # Sampled before the listen as well as after it. The scan is one point in
    # time, so a process that had the port during the listen windows and let go
    # before the end leaves an empty result -- and reporting a live receiver as
    # absent is the one outcome worse than a failure.
    local holders_before
    holders_before=$(port_holders "$device")

    if ! detect_baud "$device"; then
        # Silence carries no information by itself. The port is the SoC UART and
        # pi-gen lists it in /etc/default/gpsd on every HALPI2 marine image, so a
        # board with no module is silent, and so is one whose receiver something
        # else is consuming. Only the second is a fault, so each fault is
        # evidenced directly and everything left over is an absence.
        #
        # gpsd is left at whatever rate it already had. Guessing one is what
        # floods a receiver.
        if [ ! -e "$device" ]; then
            echo "ERROR: $device is listed in $GPSD_DEFAULTS but does not exist."
            echo "       gpsd cannot open it either. Check that the UART is"
            echo "       enabled in the boot configuration."
            return 1
        fi

        if ! port_usable "$device"; then
            echo "ERROR: $device exists but cannot be opened as a serial port."
            echo "       gpsd cannot read it either."
            return 1
        fi

        local holders
        holders=$(port_holders "$device")
        if [ -n "$holders" ]; then
            echo "ERROR: nothing heard on $device, which is held by: $holders"
            echo "       A process holding the port consumes the receiver's"
            echo "       output, which is indistinguishable from an empty port."
            return 1
        fi
        if [ -n "$holders_before" ]; then
            echo "ERROR: nothing heard on $device, which was held by"
            echo "       $holders_before when this run started. Every sample was"
            echo "       taken while another process had the port, so the silence"
            echo "       says nothing about the hardware."
            return 1
        fi
        if [ "$DETECTED_CONTENDED" -eq 1 ]; then
            echo "ERROR: nothing heard on $device, and its rate was changed by"
            echo "       another process while this run listened. The samples are"
            echo "       not evidence about the hardware."
            return 1
        fi

        # A port with traffic on it is not an empty port, whatever that traffic
        # is: a receiver at a rate outside the two candidates, or one that is not
        # u-blox at all. Calling it absent would exit 0 over a live receiver that
        # nothing then configures, which is the failure shape that hid the
        # original bug for months.
        local bytes
        bytes=$(port_byte_count "$device" "$TARGET_BAUD" || true)
        if [ "${bytes:-0}" -gt "$QUIET_MAX_BYTES" ]; then
            echo "ERROR: $device carried $bytes bytes in ${SNIFF_SECONDS}s but"
            echo "       nothing parseable at $TARGET_BAUD or $FACTORY_BAUD bps."
            echo "       Something is transmitting that this script cannot"
            echo "       address: a receiver at another rate, or not a u-blox."
            return 1
        fi

        echo "Nothing on $device and nothing holding it — no receiver fitted."
        return "$NO_RECEIVER_RC"
    fi

    local current_baud="$DETECTED_BAUD"
    RECEIVER_BAUD="$current_baud"
    echo "Receiver detected at ${current_baud} bps"

    # Reported, not fatal. The receiver rate-limits its RX for the remainder of a
    # one-second window after 100 frame errors and re-enables it at the end of
    # that window -- the notice is emitted when RX comes back, not while it is
    # gone (UBX-13003221 R28, UART section). Something is producing frame errors
    # on this line and that is worth a journal entry, but it clears itself, and
    # refusing to configure a receiver that will be listening a second later
    # helps nobody.
    if [ "$DETECTED_RX_DISABLED" -eq 1 ]; then
        echo "WARNING: receiver reported >100 frame errors in a second and briefly"
        echo "         disabled its UART RX. It re-enables itself; something on"
        echo "         this line is transmitting at the wrong rate."
    fi

    # A poll needs a reply, and a receiver filling its link cannot always deliver
    # one: its transmit buffer overflows and poll replies are among what gets
    # dropped, while set commands, travelling the other way, still land. Measured
    # at 9600, where 10 Hz oversubscribes the line eightfold and no MON-VER reply
    # arrives even with a 12 s wait. Measured again at 115200, where the link runs
    # at about half capacity and 7 of 90 polls still went unanswered.
    #
    # So the poll is advisory at every rate. Its only product is the protocol
    # version, the default is 18 and M8 hardware reports 18, and failing on a
    # missing reply costs the whole configuration -- roughly one run in twelve on
    # a receiver that is working perfectly.
    local protver protver_known=1
    if ! protver=$(probe_protver "$device" "$current_baud"); then
        protver="$DEFAULT_PROTVER"
        protver_known=0
        echo "WARNING: no UBX reply at ${current_baud} bps after $PROBE_RETRIES tries."
        echo "         Assuming protocol $protver and configuring anyway."
    fi

    if [ "$current_baud" -ne "$TARGET_BAUD" ]; then
        echo "Changing baud rate to $TARGET_BAUD..."
        run_ubxtool "$device" "$current_baud" "$protver" -S "$TARGET_BAUD" \
            || { echo "ERROR: baud change failed"; return 1; }
        sleep 1

        # Confirm where the receiver actually ended up rather than assuming the
        # switch took. Listening again is read-only, so a receiver that stayed
        # behind is found without transmitting at the rate it rejected.
        if ! detect_baud "$device" || [ "$DETECTED_BAUD" -ne "$TARGET_BAUD" ]; then
            # Only a rate we actually heard. Falling back to the pre-switch rate
            # here would be backwards: this branch is reached when the receiver
            # was found at NEITHER rate, and it was positively heard at the old
            # one moments ago -- so silence there is evidence the switch landed.
            # Asserting the abandoned rate would point gpsd at the one rate the
            # receiver is known not to be using. Empty makes main leave the
            # setting alone, which is its existing behaviour for an unknown rate.
            RECEIVER_BAUD="$DETECTED_BAUD"
            if [ "$DETECTED_RX_DISABLED" -eq 1 ]; then
                echo "WARNING: receiver reported frame errors during this run; the"
                echo "         baud command may have been sent into a rate-limited RX."
            fi
            echo "ERROR: receiver did not switch to $TARGET_BAUD (now at ${RECEIVER_BAUD:-unknown} bps)"
            return 1
        fi
        current_baud="$TARGET_BAUD"
        RECEIVER_BAUD="$current_baud"
    fi

    # Rate and model are set only now, at the target baud. 10 Hz on a 9600 link
    # oversubscribes it, and a receiver left in that state is unpollable:
    # transmitting, accepting commands, answering nothing, and looking to every
    # later boot like a receiver that is not there.
    #
    # Worth asking again at the target rate if the earlier answer went missing --
    # the link has more headroom here -- but the assignment is guarded, because a
    # failed command substitution would otherwise overwrite the assumed version
    # with an empty string and address the receiver with no protocol at all.
    if [ "$protver_known" -eq 0 ]; then
        local retry_protver
        if retry_protver=$(probe_protver "$device" "$current_baud"); then
            protver="$retry_protver"
            protver_known=1
        fi
    fi
    if [ "$protver_known" -eq 1 ]; then
        echo "Protocol version: $protver"
    else
        echo "Protocol version: $protver (assumed; the receiver never answered)"
    fi

    echo "Setting 10 Hz update rate..."
    run_ubxtool "$device" "$current_baud" "$protver" -p "CFG-RATE,$TARGET_RATE" \
        || { echo "ERROR: RATE failed"; return 1; }

    echo "Setting Sea dynamic model..."
    run_ubxtool "$device" "$current_baud" "$protver" -p "MODEL,$TARGET_MODEL" \
        || { echo "ERROR: MODEL failed"; return 1; }

    echo "Saving to BBR..."
    run_ubxtool "$device" "$current_baud" "$protver" -p SAVE \
        || { echo "ERROR: SAVE failed"; return 1; }

    echo "Successfully configured $device"
    return 0
}

# gpsd's baud lives in /etc/default/gpsd, written by pi-gen at image-build time
# and not otherwise updatable. Keep it in sync with the receiver so a stale image
# (or a leftover manual workaround) can't leave gpsd opening the port at the wrong
# baud.
#
# The rate is a parameter because gpsd is the second source of the frame-error
# flood: pointed at a receiver still at 9600, it transmits its own probes at
# 115200 and can disable the receiver's UART RX by itself. Matching gpsd to where
# the hardware actually is yields a degraded-but-working GPS rather than a
# bricked one when configuration failed.
reconcile_gpsd_speed() {
    local baud="$1"
    [ -f "$GPSD_DEFAULTS" ] || return 0

    local current
    # shellcheck source=/dev/null
    current=$(. "$GPSD_DEFAULTS" && printf '%s' "${GPSD_OPTIONS:-}")

    case " $current " in
        *" -s $baud "*) return 0 ;;
    esac

    local updated
    if printf '%s' "$current" | grep -Eq -- '-s [0-9]+'; then
        updated=$(printf '%s' "$current" | sed -E "s/-s [0-9]+/-s $baud/")
    else
        updated="${current:+$current }-s $baud"
    fi

    # Rewrite (or add) the GPSD_OPTIONS line without passing the value through a
    # sed replacement, so an option string can't corrupt or abort the edit.
    #
    # Replaced by rename, not by truncating the target and writing into it. This
    # file is what tells gpsd which device to open and what tells this script
    # which devices exist, so a half-written copy -- a full SD card, power cut
    # mid-write -- costs the GPS permanently and silently: every later boot reads
    # no DEVICES, says "nothing to do" and exits 0. The temp file is created in
    # the target's own directory so the rename cannot cross a filesystem, and it
    # inherits the original's mode and owner. The step stays best-effort: a write
    # failure must not fail a unit that already configured the receiver.
    local tmp
    tmp=$(mktemp "${GPSD_DEFAULTS}.XXXXXX") \
        || { echo "WARNING: cannot reconcile gpsd baud (mktemp failed)"; return 0; }
    # cp -p first so the temp file inherits mode and owner (POSIX; --reference is
    # a GNU extension), then rewrite its contents -- a redirect truncates without
    # touching either. Falls back to a plain copy where -p cannot preserve owner.
    if ! { { cp -p "$GPSD_DEFAULTS" "$tmp" 2>/dev/null || cp "$GPSD_DEFAULTS" "$tmp"; } \
           && { { grep -v '^GPSD_OPTIONS=' "$GPSD_DEFAULTS" || true
                  printf 'GPSD_OPTIONS="%s"\n' "$updated"; } > "$tmp"; } \
           && mv -f "$tmp" "$GPSD_DEFAULTS"; }; then
        echo "WARNING: cannot write $GPSD_DEFAULTS (left unchanged)"
        rm -f "$tmp"
        return 0
    fi
    echo "Reconciled gpsd baud to $baud in $GPSD_DEFAULTS"

    # --no-block: this unit is ordered Before=gpsd.service, so a blocking restart
    # would deadlock against gpsd's start job on the apt-upgrade path.
    if systemctl is-active --quiet gpsd.service; then
        echo "Restarting gpsd to apply new baud..."
        systemctl --no-block try-restart gpsd.service || true
    fi
}

# gpsd opens /dev/ttyAMA0 and keeps it, so a sample taken while it runs is empty
# or truncated. Leaving it there would make the unit fail on every device gpsd
# happens to be running on, naming gpsd itself as the holder -- correct, and
# useless. Take the port instead, and the holder check is left to report the
# processes that have no business on it.
#
# Boot is not the problem: this unit is ordered Before=gpsd.service, so gpsd has
# not opened anything yet. The apt-upgrade path is, because postinst restarts
# this unit on a live system. On a marine device that is the normal state --
# Signal K holds a client connection to gpsd's socket, which keeps re-activating
# gpsd.service on demand -- so the socket has to come down too, or it simply
# restarts underneath the detection.
#
# Keyed on gpsd.service, not the socket: the socket is active from early boot on
# every device and owns no hardware, so keying on it would stop and churn gpsd
# on every single boot for nothing.
GPSD_UNITS="gpsd.socket gpsd.service"
GPSD_STOPPED=0

take_port() {
    systemctl is-active --quiet gpsd.service || return 0
    echo "gpsd holds the port — stopping it for the duration"
    # Armed BEFORE the stop, not after. `systemctl stop` on two units reports
    # failure if either job fails, having already stopped the other, so setting
    # the flag on success leaves the common partial case -- socket down, service
    # stop timed out -- with nothing recording that a restore is owed. Starting a
    # unit that is already running is a no-op, so arming early is strictly safer.
    GPSD_STOPPED=1
    # shellcheck disable=SC2086  # deliberate word splitting: two unit names
    systemctl stop $GPSD_UNITS || return 1
}

# --no-block because this unit is ordered Before=gpsd.service: a blocking start
# would queue a job that waits for this unit to finish and deadlock on itself.
# Runs from an EXIT trap so a failure part-way through cannot leave gpsd down.
release_port() {
    [ "$GPSD_STOPPED" -eq 1 ] || return 0
    GPSD_STOPPED=0
    echo "Restarting gpsd"
    # shellcheck disable=SC2086  # deliberate word splitting: two unit names
    systemctl --no-block start $GPSD_UNITS \
        || echo "WARNING: could not queue gpsd restart — check gpsd.service"
}

# --- Main ---

main() {
    local uart_devices gpsd_baud="" gpsd_conflict=0 failures=0 absent=0 rc device
    uart_devices=$(get_uart_devices)

    if [ -z "$uart_devices" ]; then
        echo "No UART GNSS devices configured — nothing to do"
        return 0
    fi

    trap release_port EXIT
    take_port

    for device in $uart_devices; do
        # Capture the status from configure_device itself: after a bare `if`
        # with no else, $? is the compound's status (0), not the condition's.
        rc=0
        configure_device "$device" || rc=$?
        case "$rc" in
            0) ;;
            "$NO_RECEIVER_RC") absent=$((absent + 1)) ;;
            *)
                echo "WARNING: Failed to configure $device"
                failures=$((failures + 1))
                ;;
        esac

        # Reconcile as soon as this device's rate is known, not after the loop.
        # Between the on-wire change and this write, gpsd's configured rate is
        # stale, and anything that ends the run in that window -- a timeout kill,
        # an admin restart, shutdown -- reaches release_port, which starts gpsd
        # at the old rate and points it at a receiver that has already moved.
        if [ -n "$RECEIVER_BAUD" ]; then
            if [ -n "$gpsd_baud" ] && [ "$gpsd_baud" != "$RECEIVER_BAUD" ]; then
                # gpsd's -s is global, so two receivers at different rates cannot
                # both be served. Writing either one points gpsd at a rate the
                # other is not using, which is the flood this exists to prevent.
                echo "WARNING: $device runs at $RECEIVER_BAUD but another device"
                echo "         runs at $gpsd_baud; gpsd has one global speed, so"
                echo "         $GPSD_DEFAULTS is left untouched."
                gpsd_conflict=1
            else
                gpsd_baud="$RECEIVER_BAUD"
            fi
        fi
    done

    if [ -n "$gpsd_baud" ] && [ "$gpsd_conflict" -eq 0 ]; then
        reconcile_gpsd_speed "$gpsd_baud"
    fi

    # Explicitly, not just via the trap: the speed has to be reconciled before
    # gpsd comes back, and the trap fires after main has already returned.
    release_port

    # A detected receiver that could not be configured must leave the unit
    # failed: a success exit here means systemd reports 0/SUCCESS while the GPS
    # chain is dead. gpsd is ordered after this unit but does not require it, so
    # it starts either way.
    if [ "$failures" -ne 0 ]; then
        echo "u-blox configuration failed on $failures device(s)"
        return 1
    fi

    # An absent receiver is a hardware configuration, not a fault, so it exits 0
    # and leaves the unit active. The journal line above says which port was
    # empty, which is where someone expecting a receiver should look.
    if [ "$absent" -ne 0 ]; then
        echo "No GNSS receiver present on $absent configured device(s)"
    fi

    echo "u-blox configuration complete"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
